#93: "Делегат" -> "делегат" и изменение заглавных букв в названиях команд/комитетов
TimWCA/wca-regulations-translations pull request #112
Opened 2022-10-24 12:06 UTC by TimWCA

2022-10-24 12:18 UTC, Nevseros requested changes

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-guidelines.md
> +- 1c++) [УТОЧНЕНИЕ] делегаты WCA могут посещать соревнования, но при этом не быть указаны как делегаты WCA, назначенные на эти соревнования. Термин «делегат WCA» не применяется к ним, если только им
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-guidelines.md
> +- 2e++) [ДОПОЛНЕНИЕ] делегату WCA следует также подтверждать имя и дату рождения участника с помощью соответствующих документов (например, с помощью паспорта) у каждого нового участника на его первом
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-guidelines.md
> +- 2k6+) [УТОЧНЕНИЕ] делегаты WCA могут принять такое решение только для того, чтобы участники не нанесли ущерба соревнованиям (например, потратили время/ресурсы соревнования). Участники не должны быт
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-guidelines.md
> +- 2u1+) [ДОПОЛНЕНИЕ] Участник может участвовать по решению делегата WCA. делегат WCA должен внимательно рассмотреть справедливость этого решения.
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-guidelines.md
> +- 3k2+) [ДОПОЛНЕНИЕ] делегату WCA не следует применять указанное исключение, если он уверен, что участник пытался использовать недопустимую головоломку умышленно.
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-guidelines.md
> +- 4b1+) [НАПОМИНАНИЕ] делегату WCA запрещается перегенерировать скрамблы, фильтруя текущие. Например, делегату WCA нельзя снова генерировать скрамблы для соревнования с целью сделать их «более честны
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-guidelines.md
> +- 4f+) [РЕКОМЕНДАЦИЯ] делегату WCA следует сгенерировать достаточное для всего соревнования количество скрамблов, включая запасные скрамблы для дополнительных попыток.
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-guidelines.md
> +- 11e++) [РЕКОМЕНДАЦИЯ] делегату WCA следует записывать причину предоставления дополнительной попытки (например, на обратной стороне карточки участника).
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-guidelines.md
> +- A7g+++) [РЕКОМЕНДАЦИЯ] делегату WCA следует благоразумно давать более одной дополнительной попытки одному и тому же новому участнику. Разные дополнительные попытки следует давать за разные инцидент
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-guidelines.md
> +- B1b+) [РЕКОМЕНДАЦИЯ] делегату WCA стоит проверить повязки перед их использованием на соревновании.
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-regulations.md
> +- 1c) делегат WCA несёт ответственность за соблюдение на соревнованиях Положений WCA, а также всех применимых политик и требований. делегат WCA может передать свои обязанности кому-то из команды орга
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-regulations.md
> +- 2e) Участники должны представлять страну, гражданами которой они являются. делегату WCA следует проверить гражданство по документам участника (например, паспорту). Если обнаружено, что участник не
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-regulations.md
> +- 2j) делегат WCA может дисквалифицировать участника с конкретной дисциплины.
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-regulations.md
> +- 2k) делегат WCA может дисквалифицировать участника с некоторых дисциплин соревнования (с одной, нескольких или всех), если участник:
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-regulations.md
> +        - 2k2a) делегат WCA может дисквалифицировать (записать как DNF) любые подозрительные результаты.
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-regulations.md
> +    - 2n2) делегат WCA должен разрешить спор до начала следующего раунда дисциплины.
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-regulations.md
> +        - 4b2a) делегат WCA, назначенный на соревнования, должен давать доступ к скрамблам последующих групп команде организаторов только в том случае, если он будет временно недоступен (например, ес
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-regulations.md
> +- 11g) делегат WCA должен убедиться в наличии у официальных лиц и участников доступа к Положениям WCA и Дополнениям (например, в печатном, цифровом виде или через Интернет), к которым можно будет обр
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-regulations.md
> +- 11h) делегат WCA может потребовать от участников покинуть место проведения соревнования в случае серьёзного нарушения [Положения 2k3](regulations:regulation:2k3), принимая во внимание серьёзность с
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-regulations.md
> +        - E2e1) делегат WCA может попросить участника объяснить каждый ход в его решении, без использования скрамбла. Если участник не может дать вразумительного объяснения, попытка дисквалифицируетс
С заглавной.

2022-10-24 12:18 UTC, Nevseros commented on russian/wca-regulations.md
> +- E4) делегат WCA может решить опубликовать решение (например, фото карточки участника или последовательность сборки).
С заглавной.

2022-10-24 12:37 UTC, Nevseros approved these changes

2022-10-25 19:04 UTC, Niksson approved these changes

2022-10-25 19:08 UTC, AlexKatyukov approved these changes

2022-10-26 01:24 UTC, merged