Положения 2023-02-01: Определение элемента в 5b6
TimWCA/wca-regulations-translations pull request #139
Opened 2023-01-27 20:37 UTC by Nevseros

[Commit](https://github.com/thewca/wca-regulations/commit/f5d19c6bdaced44780b9df9b2ae066f98d1029d7#diff-956a14a4ea81ea087b348a75a65299196c5fd7fd67d16c012dbb359492b0e755R201)

2023-01-27 21:16 UTC, Niksson approved these changes

2023-01-27 22:17 UTC, AlexKatyukov requested changes, later dismissed

2023-01-27 22:17 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +    - 5b6) Определение: Элемент - это один или более полностью соединённых компонентов из группы компонентов головоломки, которые остаются соединёнными друг с другом и не перемещаются друг относитель
`Элемент` → `элемент`.

Насчёт всего остального — топ (понимаю, какая боль переводить такое), но мб чуть упростим?

`Элемент - это один или более полностью соединённых компонентов из группы компонентов головоломки, которые остаются соединёнными друг с другом...`

↓↓↓ 

`элемент - это один или несколько полностью соединённых компонентов головоломки, которые остаются соединёнными друг с другом...`

2023-01-29 12:21 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +    - 5b6) Определение: Элемент - это один или более полностью соединённых компонентов из группы компонентов головоломки, которые остаются соединёнными друг с другом и не перемещаются друг относитель
```suggestion
    - 5b6) Определение: элемент - это один или несколько полностью соединённых компонентов головоломки, которые остаются соединёнными друг с другом и не перемещаются друг относительно друга во время совершения ходов (например, крышка центрального элемента 3x3x3, угловой элемент 3x3x3 без одной цветной части, одна цветная часть углового элемента 3x3x3).
```

2023-01-30 16:08 UTC, TimWCA approved these changes

2023-01-30 16:16 UTC, merged