Положения 2023-02-01: Добавление 1h+++
TimWCA/wca-regulations-translations pull request #142
Opened 2023-01-27 21:34 UTC by Nevseros

[Commit 1](https://github.com/thewca/wca-regulations/commit/896f3984f16daa2ebf9773045996ab07c90adb71), [commit 2](https://github.com/thewca/wca-regulations/commit/0422515cf158f3691522804c707687b6e0735020)

2023-01-27 21:36 UTC, Niksson approved these changes

2023-01-28 10:49 UTC, TimWCA approved these changes

2023-01-28 11:36 UTC, Nevseros commented
Не мержить, здесь ошибка

2023-01-29 12:28 UTC, AlexKatyukov requested changes
Я вижу LGTM, но так как Катя видит ошибку, добавлю чейндж реквест, чтобы случайно не смёржил никто :)

2023-01-29 19:39 UTC, Nevseros commented
Ситуация такая, это дополнение неправильно добавили в оригинале (1h1+++), вроде как хотят фиксить. Вливаем?

2023-01-29 20:38 UTC, AlexKatyukov commented
Вливаем, держим руку на пульсе

2023-01-29 20:38 UTC, AlexKatyukov approved these changes

2023-01-29 20:38 UTC, merged