Фикс наименований ОХ и БЛД
TimWCA/wca-regulations-translations pull request #155
Opened 2023-01-28 12:42 UTC by Nevseros

Везде `Сборка вслепую` и `Сборка кубика 3x3x3 одной рукой`

2023-01-28 12:43 UTC, Niksson approved these changes

2023-01-29 12:43 UTC, AlexKatyukov requested changes

2023-01-29 12:43 UTC, AlexKatyukov commented on russian/wca-guidelines.md
> +## <article-C><one-handed><onehandedsolving> Статья C: Сборка кубика 3x3x3 одной рукой
![image](https://user-images.githubusercontent.com/18090165/215326408-c44ff32d-899a-4e10-9a01-40b429e06033.png)

Неа :)

В Положениях статья не про сборку 3x3x3 одной рукой, статья про сборку одной рукой чего угодно. А вот что фактически других дисциплин с одной рукой нет — ну что ж.

2023-01-29 12:43 UTC, AlexKatyukov commented on russian/wca-guidelines.md
> +## <article-H><multiple-blindfolded><multipleblindfoldedsolving> Статья H: Мульти-блайнд (Сборка вслепую нескольких кубов)
А вот тут не название дисциплины, а просто пояснение, я за оставить как есть (с маленькой)

2023-01-29 12:43 UTC, AlexKatyukov commented on russian/wca-guidelines.md
> +## <article-H><multiple-blindfolded><multipleblindfoldedsolving> Статья H: Мульти-блайнд (Сборка вслепую нескольких кубов)
```suggestion
## <article-H><multiple-blindfolded><multipleblindfoldedsolving> Статья H: Мульти-блайнд (сборка вслепую нескольких кубов)
```

2023-01-29 12:43 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +    - 9b1) Кубик 3x3x3, Кубик 2х2х2, Кубик 4х4х4, Кубик 5х5х5, Clock, Сборка кубика 3х3х3 одной рукой, Мегаминкс, Пираминкс, Скьюб и Square-1.
Не буду оставлять везде, это всё равно на пообсуждать, но если `Сборка кубика 3х3х3 одной рукой` — это официальное название дисциплины, то мне не нравится :(

Может, в соответствии с сайтом `3x3x3 одной рукой`? И, в соответствии: `4x4x4 вслепую` и `5x5x5 вслепую`?

2023-01-29 20:47 UTC, Nevseros commented on russian/wca-regulations.md
> +    - 9b1) Кубик 3x3x3, Кубик 2х2х2, Кубик 4х4х4, Кубик 5х5х5, Clock, Сборка кубика 3х3х3 одной рукой, Мегаминкс, Пираминкс, Скьюб и Square-1.
Давай ты просто сделаешь все suggestion'ы, а я волью :)

2023-01-31 20:17 UTC, Nevseros commented on russian/wca-regulations.md
> +- 3l) Головоломки могут иметь максимум одну цветную часть с логотипом. Исключение: для Сборок вслепую головоломки не должны иметь логотип.
```suggestion
- 3l) Головоломки могут иметь максимум одну цветную часть с логотипом. Исключение: для сборок вслепую головоломки не должны иметь логотип.
```

2023-01-31 20:19 UTC, Nevseros commented on russian/wca-regulations.md
> +## <article-C><one-handed><onehandedsolving> Статья C: Сборка кубика 3x3x3 одной рукой
```suggestion
## <article-C><one-handed><onehandedsolving> Статья C: Сборка одной рукой
```

2023-01-31 20:20 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +    - 3j3) Запрещено использовать в дисциплинах Сборки вслепую рифлёные/текстурированные цветные части, которые позволяют почувствовать ориентацию элементов головоломки.
```suggestion
    - 3j3) Запрещено использовать в дисциплинах сборки вслепую рифлёные/текстурированные цветные части, которые позволяют почувствовать ориентацию элементов головоломки.
```

2023-01-31 20:20 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +        - 4b3a) Для дисциплин Сборки вслепую скрамбл также должен ориентировать головоломку случайным образом (каждая ориентация равновероятна).
```suggestion
        - 4b3a) Для дисциплин сборки вслепую скрамбл также должен ориентировать головоломку случайным образом (каждая ориентация равновероятна).
```

2023-01-31 20:20 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +    - 5b4) Во время сборки в дисциплине Сборки вслепую (см. [Положение B4](regulations:regulation:B4)) любой ремонт должен выполняться вслепую. Штраф: дисквалификация попытки (DNF).
```suggestion
    - 5b4) Во время сборки в дисциплине сборки вслепую (см. [Положение B4](regulations:regulation:B4)) любой ремонт должен выполняться вслепую. Штраф: дисквалификация попытки (DNF).
```

2023-01-31 20:20 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +    - 9b1) Кубик 3x3x3, Кубик 2х2х2, Кубик 4х4х4, Кубик 5х5х5, Clock, Сборка кубика 3х3х3 одной рукой, Мегаминкс, Пираминкс, Скьюб и Square-1.
```suggestion
    - 9b1) Кубик 3x3x3, Кубик 2х2х2, Кубик 4х4х4, Кубик 5х5х5, Clock, Кубик 3х3х3 одной рукой, Мегаминкс, Пираминкс, Скьюб и Square-1.
```

2023-01-31 20:20 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +    - 9b3) Сборка кубика 3x3x3 вслепую, Сборка кубика 4х4х4 вслепую и Сборка кубика 5х5х5 вслепую.
```suggestion
    - 9b3) Сборка кубика 3x3x3 вслепую, Кубик 4х4х4 вслепую и Кубик 5х5х5 вслепую.
```

2023-01-31 20:20 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +- H1) Процедура такая же, как и в [Статье B](regulations:article:B) (Сборка вслепую). Ниже описаны дополнительные Положения, которые замещают соответствующие Положения в [Статье B](regulations:articl
```suggestion
- H1) Процедура такая же, как и в [Статье B](regulations:article:B) (сборка вслепую). Ниже описаны дополнительные Положения, которые замещают соответствующие Положения в [Статье B](regulations:article:B).
```

2023-01-31 20:20 UTC, AlexKatyukov commented on russian/wca-guidelines.md
> +- 3l++) [УТОЧНЕНИЕ] Раньше было разрешено использовать головоломки с логотипами для Сборки вслепую. Такие головоломки больше нельзя использовать.
```suggestion
- 3l++) [УТОЧНЕНИЕ] Раньше было разрешено использовать головоломки с логотипами для сборки вслепую. Такие головоломки больше нельзя использовать.
```

2023-01-31 20:20 UTC, AlexKatyukov commented on russian/wca-guidelines.md
> +- A5b+) [УТОЧНЕНИЕ] Во время инспекции или сборки участник может прикасаться к головоломке любой частью тела. Исключение: Сборка кубика 3x3x3 одной рукой (см. [Положение C1b](regulations:regulation:C
```suggestion
- A5b+) [УТОЧНЕНИЕ] Во время инспекции или сборки участник может прикасаться к головоломке любой частью тела. Исключение: Кубик 3x3x3 одной рукой (см. [Положение C1b](regulations:regulation:C1b)).
```

2023-01-31 20:20 UTC, AlexKatyukov commented on russian/wca-guidelines.md
> +## <article-C><one-handed><onehandedsolving> Статья C: Сборка кубика 3x3x3 одной рукой
```suggestion
## <article-C><one-handed><onehandedsolving> Статья C: Сборка одной рукой
```

2023-01-31 20:20 UTC, AlexKatyukov commented on russian/wca-guidelines.md
> +## <article-H><multiple-blindfolded><multipleblindfoldedsolving> Статья H: Мульти-блайнд (Сборка вслепую нескольких кубов)
```suggestion
## <article-H><multiple-blindfolded><multipleblindfoldedsolving> Статья H: Мульти-блайнд (сборка вслепую нескольких кубов)
```

2023-01-31 20:24 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +- H1) Процедура такая же, как и в [Статье B](regulations:article:B) (Сборка вслепую). Ниже описаны дополнительные Положения, которые замещают соответствующие Положения в [Статье B](regulations:articl
Название статьи

2023-01-31 20:27 UTC, Nevseros commented on russian/wca-regulations.md
>  ## <article-H><multiple-blindfolded><multipleblindfoldedsolving> Статья H: Мульти-блайнд (сборка вслепую нескольких кубов)
```suggestion
## <article-H><multiple-blindfolded><multipleblindfoldedsolving> Статья H: Мульти-блайнд (сборка нескольких кубов вслепую)
```

2023-01-31 20:28 UTC, AlexKatyukov approved these changes

2023-01-31 20:30 UTC, merged