Update Russian Translation to 2022 Regulations.
TimWCA/wca-regulations-translations pull request #39
Opened 2021-12-28 11:23 UTC by TimWCA

2021-12-28 11:43 UTC, Niksson commented
#1

2021-12-28 13:02 UTC, Niksson commented
Что должно быть учтено в этом PR:
https://github.com/thewca/wca-regulations/compare/official-2021-05-01...draft - основной список изменений
https://github.com/thewca/wca-regulations/pull/1039 - срочные изменения в формулировке Положения 2i

2021-12-28 13:06 UTC, TimWCA commented
> Что должно быть учтено в этом PR:
> https://github.com/thewca/wca-regulations/compare/official-2021-05-01...draft - основной список изменений
> https://github.com/thewca/wca-regulations/pull/1039 - срочные изменения в формулировке Положения 2i

Ну у нас 2i) в правильной формулировке?

2021-12-28 13:08 UTC, Niksson commented
> > Что должно быть учтено в этом PR:
> > [thewca/wca-regulations@official-2021-05-01...draft](https://github.com/thewca/wca-regulations/compare/official-2021-05-01...draft) - основной список изменений
> > [thewca/wca-regulations#1039](https://github.com/thewca/wca-regulations/pull/1039) - срочные изменения в формулировке Положения 2i
> 
> Ну у нас 2i) в правильной формулировке?

Не, это больше напоминалка, куда смотреть, чтобы не искать

2021-12-29 08:49 UTC, Niksson commented on russian/wca-regulations.md
> +        - 7f1a) Стакмат: таймер Speed Stacks Stackmat в комплекте с полноразмерным матом. Допустимые к использованию таймеры: Generation 2, Generation 3 Pro, Generation 4 Pro Timer Timer и/или Genera
Здесь два раза слово `Timer` подряд, наверное, это относится к таймеру Gen 3 Pro

2021-12-29 10:37 UTC, TimWCA commented on russian/wca-regulations.md
> +        - 7f1a) Стакмат: таймер Speed Stacks Stackmat в комплекте с полноразмерным матом. Допустимые к использованию таймеры: Generation 2, Generation 3 Pro, Generation 4 Pro Timer Timer и/или Genera
Исправлено

2021-12-30 09:09 UTC, Niksson commented on russian/wca-regulations.md
> +Перевод корректировали: [Оксана Рузаева](https://worldcubeassociation.org/results/p.php?i=2010RUZA01), [Антон Горячих](https://worldcubeassociation.org/results/p.php?i=2009GORY01), [Дмитрий Анискин](
Предлагаю также добавить @AlexKatyukov, если он не возражает

2021-12-30 09:10 UTC, Niksson commented on russian/wca-regulations.md
> +- 2i) Во время инспекции или сборки участникам запрещено использовать электронное или аудио оборудование (например, телефоны, MP3 плееры, диктофоны, дополнительное освещение), кроме стакмата или секу
В переводе положений используется слово "преинспекция". Возможно, это потребуется изменить, но предлагаю сделать это уже позже, а сейчас заменить слово на то, что используется сейчас.

2021-12-30 09:13 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +Перевод корректировали: [Оксана Рузаева](https://worldcubeassociation.org/results/p.php?i=2010RUZA01), [Антон Горячих](https://worldcubeassociation.org/results/p.php?i=2009GORY01), [Дмитрий Анискин](
Полагаюсь на ваше умение оценивать вклад. Мне кажется, что он не очень большой, но, если считаете нужным :)

2021-12-30 09:14 UTC, TimWCA commented on russian/wca-regulations.md
> +- 2i) Во время инспекции или сборки участникам запрещено использовать электронное или аудио оборудование (например, телефоны, MP3 плееры, диктофоны, дополнительное освещение), кроме стакмата или секу
Готово :)

2021-12-30 09:16 UTC, Nevseros requested changes
`A3b) Судья подготавливает таймер, при необходимости включая его и сбрасывая. Если используется таймер Generation 5 Pro, судья должен удостовериться, что он переведён в режим 2-pad mode. Также судья подготавливает секундомер для измерения преинспекции (частично замещено [Положением Y7d1](regulations:regulation:Y7d1)).`

По-хорошему бы "... переведён в режим «2-Pad mode»." Mode и так режим, а тут идет как название.

2021-12-30 09:25 UTC, TimWCA commented on russian/wca-regulations.md
> +Перевод корректировали: [Оксана Рузаева](https://worldcubeassociation.org/results/p.php?i=2010RUZA01), [Антон Горячих](https://worldcubeassociation.org/results/p.php?i=2009GORY01), [Дмитрий Анискин](
Добавим :)

2021-12-30 09:45 UTC, Nevseros approved these changes

2021-12-30 09:58 UTC, Niksson approved these changes

2021-12-30 17:40 UTC, AlexKatyukov approved these changes
Проблем не найдено. Есть предложения, воткну в issues :)

2021-12-30 17:41 UTC, merged